import Header from '@/components/header'
import "@/styles/layout.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <Header></Header>
          <div className="body">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
